# Preliminary Data Analytic Pipeline 
Provide a coded solution for each area below.  Where appropriate show output and explanations/insights.  Make sure it runs properly.
You will need to install the libraries below if required just

!pip install < lib >
* [pandas](https://pandas.pydata.org/)  
   * [Pandas Tutorials](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html) 
   * [Pandas Example](https://towardsdatascience.com/30-examples-to-master-pandas-f8a2da751fa4)
* [numpy](https://numpy.org/) 
   * [Numpy Examples](https://numpy.org/doc/stable/user/quickstart.html)
* [scikit-learn with Examples](https://scikit-learn.org/stable) 
* [ydata_profiling](https://ydata-profiling.ydata.ai/docs/master/pages/getting_started/overview.html)

In [1]:
# !pip install pandas 
# !pip install numpy 
# !pip install scikit-learn 
# !pip install ydata-profiling

In [2]:
import pandas as pd
import numpy as np
import sklearn
from ydata_profiling import ProfileReport
from ydata_profiling.utils.cache import cache_file
from pathlib import Path
from copy import deepcopy
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# Allow full view of DataFrames and Series
pd.set_option('display.max_columns', None)  # None or 1000
# pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199

## Data Integration
Use the fraud data set introduced earlier in the course

In [4]:
# data integration
df = pd.read_csv('./transactions-1.csv')

In [5]:
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,sex,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,MO,63453,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
1852390,1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,TX,77566,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
1852391,1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,WA,99323,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
1852392,1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,ID,83643,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
1852393,1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,OK,73034,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

## Format and Type
Determine the format of the file and the types of each feature.

**We see that ***Unnamed: 0*** is simply the index, so we can drop this column since Pandas generates an index upon dataframe creation**

In [6]:
## format and type
fpth = Path('./transactions-1.csv')
print('File format is {}'.format(fpth.suffix))
df = df.drop(columns=['Unnamed: 0'])
pd.set_option('display.max_rows', None)  # or 1000
print('\nThe feature types are:\n{}'.format(df.dtypes))
pd.set_option('display.max_rows', 10)  # or 1000

File format is .csv

The feature types are:
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
sex                       object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

## Analysis
Determine the dynamics of each feature (int/float - math stats, text - categorical or not)

**First we check for any nan entries**

In [7]:
for col in df.columns:
    print('{} {}'.format(df[col].isna().sum(), col))

0 trans_date_trans_time
0 cc_num
0 merchant
0 category
0 amt
0 first
0 last
0 sex
0 street
0 city
0 state
0 zip
0 lat
0 long
0 city_pop
0 job
0 dob
0 trans_num
0 unix_time
0 merch_lat
0 merch_long
0 is_fraud

**Then we check the format/type of *trans_date_trans_time*.**

In [8]:
# analysis
print(type(df['trans_date_trans_time'][0]))
print(df['trans_date_trans_time'][0])
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

<class 'str'>
2019-01-01 00:00:18

**We must preserve the cyclical nature of time within a day, and days within a year.  We will address this in the *Clean Up* section.**

**Now look at *cc_num*.**

In [39]:
# pd.set_option('display.max_rows', None)  # or 1000
# print(df.loc[df['is_fraud'] == 1, 'cc_num'].value_counts())
# pd.set_option('display.max_rows', 10)  # or 1000

***cc_num* seems to show no pattern with *is_fraud*; because there are so many different values, we will later drop this column rather than one-hot-encode.**  
**We will move on to *merchant*.**

In [40]:
# pd.set_option('display.max_rows', None)  # or 1000
# print((df.loc[df['is_fraud'] == 1, 'merchant'].value_counts() /\
#        df['merchant'].value_counts()).sort_values(ascending=False))
# pd.set_option('display.max_rows', 10)  # or 1000

***merchant* seems to show no pattern with *is_fraud*; because there are so many different values, we will later drop this column rather than one-hot-encode.**  

**Now we will examine *category*.**

In [11]:
df['category'].unique()

array(['misc_net', 'grocery_pos', 'entertainment', 'gas_transport',
       'misc_pos', 'grocery_net', 'shopping_net', 'shopping_pos',
       'food_dining', 'personal_care', 'health_fitness', 'travel',
       'kids_pets', 'home'], dtype=object)

**We will later one-hot-encode *category*.**
  
**We will later drop *first* and *last* names since they are essentially unique per data point.**  
**We will later one-hot-encode *sex* since it is categorical.**  
**We will later drop *street* since *zip*, *city*, and *state* are more meaningful categorical features for location.**  
**We will now examine *zip*.**

In [41]:
# pd.set_option('display.max_rows', None)  # or 1000
# print((df.loc[df['is_fraud'] == 1, 'zip'].value_counts() /\
#        df['zip'].value_counts()).sort_values(ascending=False))
# pd.set_option('display.max_rows', 10)  # or 1000

**Curiously, a minority set of zip codes have a 1.0 correlation with fraud, while the remaining have at least an order of magnitude less correlation.**  
**We will later one-hot encode these into either the group with 1.0 correlation, or a group for the remaining lower correlations.**
**We will now examine *city*.**

In [42]:
# pd.set_option('display.max_rows', None)  # or 1000
# print((df.loc[df['is_fraud'] == 1, 'city'].value_counts() /\
#        df['city'].value_counts()).sort_values(ascending=False))
# pd.set_option('display.max_rows', 10)  # or 1000

**This has the same correlation pattern as zip:fraud.**  
**We will later one-hot-encode these.**  
**Now we will examine state.**

In [43]:
# pd.set_option('display.max_rows', None)  # or 1000
# print((df.loc[df['is_fraud'] == 1, 'state'].value_counts() /\
#        df['state'].value_counts()).sort_values(ascending=False))
# pd.set_option('display.max_rows', 10)  # or 1000

**This has the same correlation pattern as zip:fraud, but narrowed down to a single state.**  
**We will one-hot-encode this.**  
**Now we will examine *job*.**

In [44]:
# pd.set_option('display.max_rows', None)  # or 1000
# print((df.loc[df['is_fraud'] == 1, 'job'].value_counts() /\
#        df['job'].value_counts()).sort_values(ascending=False))
# pd.set_option('display.max_rows', 10)  # or 1000

**The same pattern emerges here.**  
**We will later one-hot-encode the jobs with 1.0 correlation against a group comprised of the lower correlations.**  
  
**We now convert *dob* to pandas datetime objects and examine.**

In [16]:
df['dob'] = pd.to_datetime(df['dob'])
print(df['dob'])

0         1988-03-09
1         1978-06-21
2         1962-01-19
3         1967-01-12
4         1986-03-28
             ...
1852389   1966-02-13
1852390   1999-12-27
1852391   1981-11-29
1852392   1965-12-15
1852393   1993-05-10
Name: dob, Length: 1852394, dtype: datetime64[ns]

**We will later extract the year into its own feature, and encode month/day to preserve its cyclical nature.**

**We will later drop *trans_num* and *unix_time*.**  
***trans_num* is unique per data point, and date/time will be better captured by the re-coding of *trans_date_trans_time* in the next section.**

## Clean up
* Find and List number of blank entries and outliers/errors
* Take corrective actions and provide justification
* Remove unnecessary features
* If a categorical approach breakout the input features (X) from the output features (y)

**In the previous section we discussed the need to re-code date/time to preserve the ordering of year, and also the cyclical nature of days within a year as well as seconds within a day.**  
**We convert *trans_date_trans_time* to pandas datetime objects to allow easier separation of calendar day and time.**

In [17]:
print(type(df['trans_date_trans_time'][0]))
print(df['trans_date_trans_time'][0])

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
2019-01-01 00:00:18

**Now create a year column**

In [18]:
df['year'] = df['trans_date_trans_time'].dt.year
print(df['year'])

0          2019
1          2019
2          2019
3          2019
4          2019
           ...
1852389    2020
1852390    2020
1852391    2020
1852392    2020
1852393    2020
Name: year, Length: 1852394, dtype: int64

**Now create a day of year column**  
**This is used for sine/cosine facetization, and will later be dropped.**

In [19]:
df['day_of_year'] = df['trans_date_trans_time'].dt.day_of_year
print(df['day_of_year'])

0            1
1            1
2            1
3            1
4            1
          ...
1852389    366
1852390    366
1852391    366
1852392    366
1852393    366
Name: day_of_year, Length: 1852394, dtype: int64

**Now create a seconds in day column**  
**This is used for sine/cosine facetization, and will later be dropped.**

In [20]:
df['sec_of_day'] = df['trans_date_trans_time'].dt.second +\
        60 * df['trans_date_trans_time'].dt.minute +\
        3600 * df['trans_date_trans_time'].dt.hour
print(df['sec_of_day'])

0             18
1             44
2             51
3             76
4            186
           ...
1852389    86347
1852390    86349
1852391    86355
1852392    86364
1852393    86374
Name: sec_of_day, Length: 1852394, dtype: int64

**Now we can expand both *day_of_year* and *sec_of_day* out to sine and cosine facets, in order to preserve their cyclical nature.**

In [21]:
# First do day_of_year
df['doy_x'] =\
        np.cos(2 * np.pi * df.loc[df['trans_date_trans_time'].dt.is_leap_year, 'day_of_year'] /\
        366)  # x component of day_of_year for leap years
df.loc[~df['trans_date_trans_time'].dt.is_leap_year, 'doy_x'] =\
        np.cos(2 * np.pi * df.loc[~df['trans_date_trans_time'].dt.is_leap_year, 'day_of_year'] /\
        365)  # x component of day_of_year for non leap years
df['doy_y'] =\
        np.sin(2 * np.pi * df.loc[df['trans_date_trans_time'].dt.is_leap_year, 'day_of_year'] /\
        366)  # y component of day_of_year for leap years
df.loc[~df['trans_date_trans_time'].dt.is_leap_year, 'doy_y'] =\
        np.sin(2 * np.pi * df.loc[~df['trans_date_trans_time'].dt.is_leap_year, 'day_of_year'] /\
        365)  # y component of day_of_year for non leap years

# Now do sec_of_day
df['sod_x'] = np.cos(2 * np.pi * df['sec_of_day'] / 86400)  # x component of sec_of_day
df['sod_y'] = np.sin(2 * np.pi * df['sec_of_day'] / 86400)  # x component of sec_of_day

print(df['doy_x'])
print(df['doy_y'])
print(df['sod_x'])
print(df['sod_y'])

0          0.999852
1          0.999852
2          0.999852
3          0.999852
4          0.999852
             ...
1852389    1.000000
1852390    1.000000
1852391    1.000000
1852392    1.000000
1852393    1.000000
Name: doy_x, Length: 1852394, dtype: float64
0          1.721336e-02
1          1.721336e-02
2          1.721336e-02
3          1.721336e-02
4          1.721336e-02
               ...
1852389   -2.449294e-16
1852390   -2.449294e-16
1852391   -2.449294e-16
1852392   -2.449294e-16
1852393   -2.449294e-16
Name: doy_y, Length: 1852394, dtype: float64
0          0.999999
1          0.999995
2          0.999993
3          0.999985
4          0.999909
             ...
1852389    0.999993
1852390    0.999993
1852391    0.999995
1852392    0.999997
1852393    0.999998
Name: sod_x, Length: 1852394, dtype: float64
0          0.001309
1          0.003200
2          0.003709
3          0.005527
4          0.013526
             ...
1852389   -0.003854
1852390   -0.003709
1852391   -0.003272
1852392   -0.002618
1852393   -0.001891
Name: sod_y, Length: 1852394, dtype: float64

**Now we can drop *trans_date_trans_time* as well as the temporarily created columns.**

In [22]:
df = df.drop(columns=['trans_date_trans_time', 'day_of_year', 'sec_of_day'])

**Now drop *cc_num*, *merchant*, *first*, *last*, and *street*, according to the discussion in the previous section.**

In [23]:
df = df.drop(columns=['cc_num', 'merchant', 'first', 'last', 'street'])

**Now one-hot-encode *category*, *sex*, *zip*, *city*, *state*, and *job* for the reasons discussed in the previous section.**

In [24]:
df = pd.get_dummies(data=df, columns=['category', 'sex'])

***category* and *sex* are done, now move on to *zip*, *city*, *state*, and *job*.**

***zip* is done, now repeat the process for *city*, *state*, and *job*.**

In [25]:
def ohe(df, params):
    for param in params:
        df['{}_cor'.format(param)] = 0
        valscounts = (df.loc[df['is_fraud'] == 1, '{}'.format(param)].value_counts() /\
               df['{}'.format(param)].value_counts()).sort_values(ascending=False) == 1.0
        truevals = []
        for zc, bval in valscounts.items():
            if bval == True:
                truevals.append(zc)

        df.loc[df['{}'.format(param)].isin(truevals), '{}_cor'.format(param)] = 1
        print(df['{}_cor'.format(param)].value_counts())
        df = pd.get_dummies(data=df, columns=['{}_cor'.format(param)])
        df = df.drop(columns=['{}'.format(param)])

    return df
        
df = ohe(df, ['zip', 'city', 'state', 'job'])

0    1851517
1        877
Name: zip_cor, dtype: int64
0    1851685
1        709
Name: city_cor, dtype: int64
0    1852385
1          9
Name: state_cor, dtype: int64
0    1852157
1        237
Name: job_cor, dtype: int64

In [26]:
for col in df.columns:
    if col[-1] == '0':
        df = df.drop(columns=[col])

**Now re-code *dob* as discussed above.**

In [27]:
df['dob_year'] = df['dob'].dt.year
print(df['dob_year'])

0          1988
1          1978
2          1962
3          1967
4          1986
           ...
1852389    1966
1852390    1999
1852391    1981
1852392    1965
1852393    1993
Name: dob_year, Length: 1852394, dtype: int64

In [28]:
# create a temporary column for the day of year for the date of birth
# this will be deleted after sine/cosine facetization
df['dob_doy'] = df['dob'].dt.day_of_year
print(df['dob_doy'])

0           69
1          172
2           19
3           12
4           87
          ...
1852389     44
1852390    361
1852391    333
1852392    349
1852393    130
Name: dob_doy, Length: 1852394, dtype: int64

In [29]:
# now sine/cosine facetize
df['dob_doy_x'] =\
        np.cos(2 * np.pi * df.loc[df['dob'].dt.is_leap_year, 'dob_doy'] /\
        366)  # x component of day_of_year for leap years
df.loc[~df['dob'].dt.is_leap_year, 'dob_doy_x'] =\
        np.cos(2 * np.pi * df.loc[~df['dob'].dt.is_leap_year, 'dob_doy'] /\
        365)  # x component of day_of_year for non leap years
df['dob_doy_y'] =\
        np.sin(2 * np.pi * df.loc[df['dob'].dt.is_leap_year, 'dob_doy'] /\
        366)  # y component of day_of_year for leap years
df.loc[~df['dob'].dt.is_leap_year, 'dob_doy_y'] =\
        np.sin(2 * np.pi * df.loc[~df['dob'].dt.is_leap_year, 'dob_doy'] /\
        365)  # y component of day_of_year for non leap years

In [30]:
df = df.drop(columns=['dob', 'dob_doy'])

**Now drop *trans_num* and *unix_time* as discussed above*.**

In [31]:
df = df.drop(columns=['trans_num', 'unix_time'])

**Now check the cleaned dataframe**

In [32]:
df

,amt,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,doy_x,doy_y,sod_x,sod_y,category_entertainment,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,sex_F,sex_M,zip_cor_1,city_cor_1,state_cor_1,job_cor_1,dob_year,dob_doy_x,dob_doy_y
0,4.97,36.0788,-81.1781,3495,36.011293,-82.048315,0,2019,0.999852,1.721336e-02,0.999999,0.001309,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1988,0.376728,0.926324
1,107.23,48.8878,-118.2105,149,49.159047,-118.186462,0,2019,0.999852,1.721336e-02,0.999995,0.003200,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1978,-0.983709,0.179767
2,220.11,42.1808,-112.2620,4154,43.150704,-112.154481,0,2019,0.999852,1.721336e-02,0.999993,0.003709,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1962,0.946988,0.321270
3,45.00,46.2306,-112.1138,1939,47.034331,-112.561071,0,2019,0.999852,1.721336e-02,0.999985,0.005527,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1967,0.978740,0.205104
4,41.96,38.4207,-79.4629,99,38.674999,-78.632459,0,2019,0.999852,1.721336e-02,0.999909,0.013526,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1986,0.073095,0.997325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,43.77,40.4931,-91.8912,519,39.946837,-91.333331,0,2020,1.000000,-2.449294e-16,0.999993,-0.003854,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1966,0.726608,0.687053
1852390,111.84,29.0393,-95.4401,28739,29.661049,-96.186633,0,2020,1.000000,-2.449294e-16,0.999993,-0.003709,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1999,0.997630,-0.068802
1852391,86.88,46.1966,-118.9017,3684,46.658340,-119.715054,0,2020,1.000000,-2.449294e-16,0.999995,-0.003272,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1981,0.852078,-0.523416
1852392,7.99,44.6255,-116.4493,129,44.470525,-117.080888,0,2020,1.000000,-2.449294e-16,0.999997,-0.002618,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1965,0.962309,-0.271958
1852393,38.13,35.6665,-97.4798,116001,36.210097,-97.036372,0,2020,1.000000,-2.449294e-16,0.999998,-0.001891,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1993,-0.618671,0.785650

## Normalize
Dont worry about text features but you must normalize the numeric features. 
* Provide rationale as to why the particular normalization feature was selected.

**We will use mean standardization.  This puts all values roughly on the scale of both the one-hot-encoded features as well as the sine/cosine facetized datetime features.**  
**Mean standardization is also outlier resilient.**

In [33]:
std_scaler = StandardScaler()
cols2std = ['amt', 'lat', 'long', 'city_pop', 'merch_lat', 'merch_long', 'year', 'dob_year']
df[cols2std] = std_scaler.fit_transform(df[cols2std])

**Now check the normalized dataframe.**

In [34]:
df

,amt,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,doy_x,doy_y,sod_x,sod_y,category_entertainment,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,sex_F,sex_M,zip_cor_1,city_cor_1,state_cor_1,job_cor_1,dob_year,dob_doy_x,dob_doy_y
0,-0.408741,-0.485167,0.658263,-0.282429,-0.495080,0.594463,0,-1.001455,0.999852,1.721336e-02,0.999999,0.001309,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0.845898,0.376728,0.926324
1,0.233378,2.040531,-2.035415,-0.293527,2.080082,-2.031915,0,-1.001455,0.999852,1.721336e-02,0.999995,0.003200,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0.270874,-0.983709,0.179767
2,0.942184,0.718034,-1.602731,-0.280243,0.903268,-1.593535,0,-1.001455,0.999852,1.721336e-02,0.999993,0.003709,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,-0.649165,0.946988,0.321270
3,-0.157381,1.516580,-1.591951,-0.287590,1.663928,-1.623084,0,-1.001455,0.999852,1.721336e-02,0.999985,0.005527,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,-0.361653,0.978740,0.205104
4,-0.176470,-0.023388,0.783024,-0.293693,0.026642,0.842714,0,-1.001455,0.999852,1.721336e-02,0.999909,0.013526,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0.730894,0.073095,0.997325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,-0.165105,0.385251,-0.120991,-0.292300,0.275748,-0.080336,0,0.998547,1.000000,-2.449294e-16,0.999993,-0.003854,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,-0.419155,0.726608,0.687053
1852390,0.262326,-1.873227,-0.379132,-0.198697,-1.738860,-0.433054,0,0.998547,1.000000,-2.449294e-16,0.999993,-0.003709,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1.478425,0.997630,-0.068802
1852391,0.105595,1.509876,-2.085692,-0.281802,1.590285,-2.143007,0,0.998547,1.000000,-2.449294e-16,0.999995,-0.003272,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0.443381,0.852078,-0.523416
1852392,-0.389777,1.200084,-1.907308,-0.293593,1.161773,-1.951567,0,0.998547,1.000000,-2.449294e-16,0.999997,-0.002618,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,-0.476658,0.962309,-0.271958
1852393,-0.200520,-0.566465,-0.527497,0.090741,-0.456142,-0.494810,0,0.998547,1.000000,-2.449294e-16,0.999998,-0.001891,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1.133411,-0.618671,0.785650

## Feature and Label Selection
Down select from your data, the input features and label(s)

***street*, *trans_num*, *unix_time*, *cc_num*, *merchant*, *first*, and *last* were dropped during the *Clean Up* section, for reasons discussed in the *Analysis* section.**

## Split into 3 data sets for training, validation, and test (Explain your % for each)

**We will use %80 train, %10 validation, and %10 split.**  
**Although the dataset is very large, we will not use a smaller validation+test percentage because there are relatively few *is_fraud=1* data points.**  
**It is necessary to straify on *is_fraud*.**

In [35]:
Y = df['is_fraud'].to_numpy()
X = df.drop(columns=['is_fraud']).to_numpy()
X_train, X_test, Y_train, Y_test =\
        train_test_split(X, Y, test_size=0.10, stratify=Y)
X_train, X_val, Y_train, Y_val =\
        train_test_split(X_train, Y_train, test_size=1/9, stratify=Y_train)

print('train/val/test data set sizes:\n')
print('X: {} {} {}'.format(X_train.shape, X_val.shape, X_test.shape))
print('Y: {} {} {}'.format(Y_train.shape, Y_val.shape, Y_test.shape))

train/val/test data set sizes:

X: (1481914, 34) (185240, 34) (185240, 34)
Y: (1481914,) (185240,) (185240,)

In [36]:
from sklearn.metrics import f1_score, roc_auc_score
from sklearn.ensemble import RandomForestClassifier

# we will use a random forest
for min_samples_split in range(2, 11):
    n_estimators = 100
    max_features = 'sqrt'
    model = RandomForestClassifier(n_jobs = -1,
                                      n_estimators = n_estimators,
                                      min_samples_split = min_samples_split,
                                      max_features = max_features,
                                      verbose = 1)
    model.fit(X_train, Y_train)
    Y_pred_train = model.predict(X_train)
    Y_pred_val = model.predict(X_val)

    # we will use F1 score as the first performance metric
    F1_train = f1_score(Y_train, Y_pred_train)
    F1_val = f1_score(Y_val, Y_pred_val)

    # ROC AUC score will be the second performance metric
    ROCAUC_train = roc_auc_score(Y_train, Y_pred_train)
    ROCAUC_val = roc_auc_score(Y_val, Y_pred_val)

    print('min_samples_split: {}'.format(min_samples_split))
    print('F1_score train: {}, val: {}\nROCAUC train: {}, val: {}'.\
          format(F1_train, F1_val, ROCAUC_train, ROCAUC_val))

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   21.7s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.3min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.6s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    2.0s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.3s finished

min_samples_split: 2
F1_score train: 0.9999352373550936, val: 0.8564760793465578
ROCAUC train: 0.9999352415490221, val: 0.8802701807883154

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   20.7s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.2min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.6s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    2.0s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.2s finished

min_samples_split: 3
F1_score train: 0.9963603275705186, val: 0.8650839606253619
ROCAUC train: 0.9963735267452403, val: 0.8870059320836522

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   20.3s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.3min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.7s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    2.4s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.2s finished

min_samples_split: 4
F1_score train: 0.9820722383337728, val: 0.8599766627771296
ROCAUC train: 0.9824501206163856, val: 0.8818327249415333

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   19.7s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.2min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.6s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    2.1s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.3s finished

min_samples_split: 5
F1_score train: 0.9612642905178211, val: 0.8642691415313224
ROCAUC train: 0.9628279708014799, val: 0.8859723759896472

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   20.8s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.2min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.5s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    1.9s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.2s finished

min_samples_split: 6
F1_score train: 0.9447098976109215, val: 0.863953488372093
ROCAUC train: 0.9481254282491931, val: 0.8849415332316887

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   19.8s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.2min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.6s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    2.3s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.3s finished

min_samples_split: 7
F1_score train: 0.9314443676572218, val: 0.8589743589743589
ROCAUC train: 0.9364038094535855, val: 0.88182729826944

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   20.7s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.2min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.5s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    1.9s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.3s finished

min_samples_split: 8
F1_score train: 0.9263011797362942, val: 0.8644560791157649
ROCAUC train: 0.9321928142969436, val: 0.8849442465677354

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   20.0s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.2min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.6s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    2.1s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.3s finished

min_samples_split: 9
F1_score train: 0.9178494022233099, val: 0.864298194525335
ROCAUC train: 0.9250683671835308, val: 0.8844288251887562

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   20.9s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.3min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.5s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    1.9s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.3s finished

min_samples_split: 10
F1_score train: 0.9103448275862069, val: 0.8564733450497949
ROCAUC train: 0.9188505383838079, val: 0.8787266299874245

**regularizing by increasing *min_samples_split* lowered the training performance but did not raise the testing performance.**  
  
**Nonetheless we will use *min_samples_split*=10 for testing, in order to keep training and testing performance closer together.**

In [38]:
n_estimators = 100
min_samples_split = 10
max_features = 'sqrt'
model = RandomForestClassifier(n_jobs = -1,
                                  n_estimators = n_estimators,
                                  min_samples_split = min_samples_split,
                                  max_features = max_features,
                                  verbose = 1)
model.fit(X_train, Y_train)
Y_pred_train = model.predict(X_train)
Y_pred_test = model.predict(X_test)

# we will use F1 score as the first performance metric
F1_train = f1_score(Y_train, Y_pred_train)
F1_test = f1_score(Y_test, Y_pred_test)

# ROC AUC score will be the second performance metric
ROCAUC_train = roc_auc_score(Y_train, Y_pred_train)
ROCAUC_test = roc_auc_score(Y_test, Y_pred_test)

print('min_samples_split: {}'.format(min_samples_split))
print('F1_score train: {}, test: {}\nROCAUC train: {}, test: {}'.\
      format(F1_train, F1_test, ROCAUC_train, ROCAUC_test))

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   18.8s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  1.2min finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.5s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    2.0s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 100 out of 100 | elapsed:    0.3s finished

min_samples_split: 10
F1_score train: 0.9108172738781825, test: 0.8276684555754322
ROCAUC train: 0.9193035083720366, test: 0.8595366521791392

**Both F1 and ROC AUC scores are on the same scale, and are assessed similarly.**  

**>0.8 is often considered very good, while >0.9 is often considred excellent.**  

**The model training performance is >0.9 while in testing it is >0.8.  I'll consider this effective in capturing the relationship between transaction data and fraud.**

**To improve performance, a neural network could be leveraged.  To make this feasible, training would leverage a GPU.  The network should also have 2 or 3 hidden layers, but likely no more.  This is because 2 hidden layers can approximate any function, while 4 hidden layers very infrequently provides added benefit.  Dropout should be employed as well to guard against overfitting.  Tensorflow would be a good library to use for this.  Sklearn would be inappropriate, since GPU computing is not an option there.**